### ISSUE TITLE
Quest

### ISSUE THREAD

**Issue by VincentLTech** [SkillsCraft/Minecraft-Forbidden-Adventures#1]
### SkillsCraft Network Support ###
---

<Enter your responses for short response questions in the empty line BELOW the question.>
<Please do not use or remove the less than or greater than signs in this ticket.>
<Before you submit a ticket, make sure to do all you can to resolve the issue yourself.>

# Type of Ticket #
<Replace the space between the square brackets with an X in the box in the area you need help in.>
Quest Crafting Completion
- [ ] Report a Bug or Glitch <Please go in detail about how to reproduce the bug or glitch in the description.>
- [ ] Report a Player <Provide evidence and describe how the player broke the rules.>I craft a forge hammer to complete the quest but it doesn't detect its completion.
- [ ] Make a Suggestion <Describe what you would like to see added in SkillsCraft Network.>
- [x] Quest Crafting Completion <An administrator will verify that you have crafted the item. Provide evidence in the description that you have the item.>

- [ ] Other issue: <Name your issue next to the asterisks in the space below this line. End your response with two asterisks.>
**
# Description #
<Describe your issue in the space above the three dashes. Do not type on the dashes. Provide evidence if necessary. Drag and drop images here to upload them.>

![image](https://user-images.githubusercontent.com/35178680/34644362-333bc5fa-f303-11e7-8e57-2113b7493334.png)

---
## Minecraft Username ##
GalacticKnight
## Game Version ##
1.1.10
## Have you added or removed any mods or resource packs? ##
<Please list the mods or resource packs that you have added or removed if your answer is Yes.>
No

## Have you done everything you can to solve the issue yourself? ##
<If the answers for this question and the following questions are No do not submit an Issue until you can say Yes to all three.>
Yes

## Have you checked to make sure the issue doesn't already exist in the Issue Tracker? ##
Yes

## Is your Chunk Loading option in the Options set to Default? ##
Yes

**Comment by GalacticKnight** [comment]
The quest for industrialcraft 2 does not detect my completion of my task.

**Comment by SkillsCraft** [comment]
Manually forced the quest completion.

Closing the ticket.
